// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScrHome
void ui_ScrHome_screen_init(void);
lv_obj_t * ui_ScrHome;
lv_obj_t * ui_FullScreen;
void ui_event_FullScreen_Sidebar3_butTemp2(lv_event_t * e);
void ui_event_FullScreen_Sidebar3_butAQ2(lv_event_t * e);
lv_obj_t * ui_count;
lv_obj_t * ui_StartLog;
lv_obj_t * ui_startLab;
lv_obj_t * ui_wifiLab;
lv_obj_t * ui_ipLab;
lv_obj_t * ui_timeLabLog;
lv_obj_t * ui_influxLab;
lv_obj_t * ui_timeLab;
lv_obj_t * ui_AirPanel;
lv_obj_t * ui_tempPanel;
lv_obj_t * ui_tempTitle;
lv_obj_t * ui_tempLab;
lv_obj_t * ui_hmPanel;
lv_obj_t * ui_humTitle;
lv_obj_t * ui_humLab;
lv_obj_t * ui_aqPanel;
lv_obj_t * ui_aqTitle;
lv_obj_t * ui_aqLab;
lv_obj_t * ui_pmPanel;
lv_obj_t * ui_pmTitle;
lv_obj_t * ui_pmLab;
lv_obj_t * ui_DoorsPanel;
lv_obj_t * ui_doubleGdoorPanel;
lv_obj_t * ui_doublGdoorTitle;
lv_obj_t * ui_doubleGdoorLab;
lv_obj_t * ui_outsidePdoorPanel;
lv_obj_t * ui_outsidePdoorTitle;
lv_obj_t * ui_outsidePdoorLab;
lv_obj_t * ui_shopPdoorPanel;
lv_obj_t * ui_shopPdoorTitle;
lv_obj_t * ui_ShopPdoorLab;
lv_obj_t * ui_singleGdoorPanel;
lv_obj_t * ui_singleGdoorTitle;
lv_obj_t * ui_singleGdoorLab;
lv_obj_t * ui_VentPanel;
lv_obj_t * ui_ventTitle;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Container3;
lv_obj_t * ui_ventStatTitle;
lv_obj_t * ui_ventStatLab;
lv_obj_t * ui_ButVentOff;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Container4;
lv_obj_t * ui_ventTimerTitle;
lv_obj_t * ui_ventTimerLab;
lv_obj_t * ui_ButVent5m;
lv_obj_t * ui_Label5;
lv_obj_t * ui_HeatPanel;
lv_obj_t * ui_heatTitle;
lv_obj_t * ui_ButVent5m1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_ButVentOff1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container1;
lv_obj_t * ui_ButHeatUp;
lv_obj_t * ui_heatLab;
lv_obj_t * ui_ButHeatDown;
lv_obj_t * ui_Container2;
lv_obj_t * ui_heatStatTitle;
lv_obj_t * ui_heatStatLab;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label14;


// SCREEN: ui_ScrCharts
void ui_ScrCharts_screen_init(void);
lv_obj_t * ui_ScrCharts;
lv_obj_t * ui_FullScreen1;
void ui_event_FullScreen1_Sidebar3_butHome2(lv_event_t * e);
void ui_event_FullScreen1_Sidebar3_butAQ2(lv_event_t * e);
lv_obj_t * ui_Chart1;
void ui_event_but6H(lv_event_t * e);
lv_obj_t * ui_but6H;
lv_obj_t * ui_Label3;
void ui_event_but1H(lv_event_t * e);
lv_obj_t * ui_but1H;
lv_obj_t * ui_Label7;
void ui_event_but3H(lv_event_t * e);
lv_obj_t * ui_but3H;
lv_obj_t * ui_Label6;
void ui_event_butTemp(lv_event_t * e);
lv_obj_t * ui_butTemp;
lv_obj_t * ui_Label8;
void ui_event_butAQ(lv_event_t * e);
lv_obj_t * ui_butAQ;
lv_obj_t * ui_Label9;
void ui_event_butPM(lv_event_t * e);
lv_obj_t * ui_butPM;
lv_obj_t * ui_Label10;
void ui_event_butHum(lv_event_t * e);
lv_obj_t * ui_butHum;
lv_obj_t * ui_Label11;
lv_obj_t * ui_LoadingPanel;
lv_obj_t * ui_loadingLab;
lv_obj_t * ui_Label12;


// SCREEN: ui_ScrTBD
void ui_ScrTBD_screen_init(void);
lv_obj_t * ui_ScrTBD;
lv_obj_t * ui_FullScreen2;
void ui_event_FullScreen2_Sidebar3_butHome2(lv_event_t * e);
void ui_event_FullScreen2_Sidebar3_butTemp2(lv_event_t * e);
lv_obj_t * ui_Label4;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_736952691[1] = {&ui_img_2110918543};
const lv_img_dsc_t * ui_imgset_1703005419[1] = {&ui_img_267769087};
const lv_img_dsc_t * ui_imgset_298057525[1] = {&ui_img_2127381671};
const lv_img_dsc_t * ui_imgset_406222076[1] = {&ui_img_347167274};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_FullScreen_Sidebar3_butTemp2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrCharts, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrCharts_screen_init);
    }
}
void ui_event_FullScreen_Sidebar3_butAQ2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrTBD, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrTBD_screen_init);
    }
}
void ui_event_FullScreen1_Sidebar3_butHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrHome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrHome_screen_init);
    }
}
void ui_event_FullScreen1_Sidebar3_butAQ2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrTBD, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrTBD_screen_init);
    }
}
void ui_event_but6H(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chart6H(e);
    }
}
void ui_event_but1H(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chart1H(e);
    }
}
void ui_event_but3H(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chart3H(e);
    }
}
void ui_event_butTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chartTemp(e);
    }
}
void ui_event_butAQ(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chartAQ(e);
    }
}
void ui_event_butPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chartPM(e);
    }
}
void ui_event_butHum(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        chartHum(e);
    }
}
void ui_event_FullScreen2_Sidebar3_butHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrHome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrHome_screen_init);
    }
}
void ui_event_FullScreen2_Sidebar3_butTemp2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScrCharts, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScrCharts_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScrHome_screen_init();
    ui_ScrCharts_screen_init();
    ui_ScrTBD_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScrHome);
}
