// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    extern lv_obj_t *ui_Screen1;
    extern lv_obj_t *ui_FullScreen;
    extern lv_obj_t *ui_Label1;
    // SCREEN: ui_Screen2
    void ui_Screen2_screen_init(void);
    extern lv_obj_t *ui_Screen2;
    extern lv_obj_t *ui_FullScreen1;
    extern lv_obj_t *ui_Label3;
    // SCREEN: ui_Screen3
    void ui_Screen3_screen_init(void);
    extern lv_obj_t *ui_Screen3;
    extern lv_obj_t *ui_FullScreen2;
    extern lv_obj_t *ui_Label4;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_home_png); // assets\home.png

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
