// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void butVentFanOff(lv_event_t * e);
void butVentFan5m(lv_event_t * e);
void chart6H(lv_event_t * e);
void chart1H(lv_event_t * e);
void chart3H(lv_event_t * e);
void chartTemp(lv_event_t * e);
void chartAQ(lv_event_t * e);
void chartPM(lv_event_t * e);
void chartHum(lv_event_t * e);
void keyboardEnter(lv_event_t * e);
void timeoutChange(lv_event_t * e);
void wificon(lv_event_t * e);
void mqttCon(lv_event_t * e);
void reboot(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
