// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScrSettings_screen_init(void)
{
    ui_ScrSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FullScreen2 = ui_FullScreen_create(ui_ScrSettings);
    lv_obj_set_x(ui_FullScreen2, 0);
    lv_obj_set_y(ui_FullScreen2, 0);




    lv_obj_set_style_bg_color(ui_comp_get_child(ui_FullScreen2, UI_COMP_FULLSCREEN_SIDEBAR3_BUTAQ2), lv_color_hex(0xA6A6A6),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_FullScreen2, UI_COMP_FULLSCREEN_SIDEBAR3_BUTAQ2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label4 = lv_label_create(ui_comp_get_child(ui_FullScreen2, UI_COMP_FULLSCREEN_CONTENTCONTAINER));
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Settings Page");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTabView = lv_tabview_create(ui_comp_get_child(ui_FullScreen2, UI_COMP_FULLSCREEN_CONTENTCONTAINER), LV_DIR_TOP,
                                      50);
    lv_obj_set_width(ui_setTabView, lv_pct(100));
    lv_obj_set_height(ui_setTabView, lv_pct(100));
    lv_obj_set_align(ui_setTabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_ventTabPage = lv_tabview_add_tab(ui_setTabView, "Ventilation Settings");
    lv_obj_set_style_border_color(ui_ventTabPage, lv_color_hex(0x204052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ventTabPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ventTabPage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ventTabPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ventTabPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ventTabPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ventTabPage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ventSetPanel = lv_obj_create(ui_ventTabPage);
    lv_obj_set_width(ui_ventSetPanel, lv_pct(49));
    lv_obj_set_height(ui_ventSetPanel, lv_pct(100));
    lv_obj_set_flex_flow(ui_ventSetPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ventSetPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ventSetPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ventSetPanel, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ventSetPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ventSetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ventSetPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ventSetPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ventSetPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ventSetPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempCont = lv_obj_create(ui_ventSetPanel);
    lv_obj_remove_style_all(ui_tempCont);
    lv_obj_set_width(ui_tempCont, lv_pct(100));
    lv_obj_set_height(ui_tempCont, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_tempCont, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_tempCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_tempCont);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 7);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, lv_pct(95));
    lv_obj_set_height(ui_Container10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Target min temp (F):   ");

    ui_targTempMinTA = lv_textarea_create(ui_Container10);
    lv_obj_set_width(ui_targTempMinTA, 40);
    lv_obj_set_height(ui_targTempMinTA, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_targTempMinTA, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_targTempMinTA, NULL);
    else lv_textarea_set_accepted_chars(ui_targTempMinTA, "0123456789");
    lv_textarea_set_max_length(ui_targTempMinTA, 2);
    lv_textarea_set_placeholder_text(ui_targTempMinTA, "--");
    lv_textarea_set_one_line(ui_targTempMinTA, true);
    lv_obj_clear_flag(ui_targTempMinTA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_targTempMinTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_targTempMinTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_targTempMinTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_targTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_targTempMinTA, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_targTempMinTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_targTempMinTA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_targTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_targTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_targTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_targTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_targTempMinTA, lv_color_hex(0xA4A5A4), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_targTempMinTA, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, lv_pct(95));
    lv_obj_set_height(ui_Container11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Absolute min temp (F):   ");

    ui_absTempMinTA = lv_textarea_create(ui_Container11);
    lv_obj_set_width(ui_absTempMinTA, 40);
    lv_obj_set_height(ui_absTempMinTA, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_absTempMinTA, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_absTempMinTA, NULL);
    else lv_textarea_set_accepted_chars(ui_absTempMinTA, "0123456789");
    lv_textarea_set_max_length(ui_absTempMinTA, 2);
    lv_textarea_set_placeholder_text(ui_absTempMinTA, "--");
    lv_textarea_set_one_line(ui_absTempMinTA, true);
    lv_obj_clear_flag(ui_absTempMinTA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_absTempMinTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_absTempMinTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_absTempMinTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_absTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_absTempMinTA, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_absTempMinTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_absTempMinTA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_absTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_absTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_absTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_absTempMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_absTempMinTA, lv_color_hex(0xA4A5A4), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_absTempMinTA, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(95));
    lv_obj_set_height(ui_Container7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Fan on time (min):   ");

    ui_fanOnTempTA = lv_textarea_create(ui_Container7);
    lv_obj_set_width(ui_fanOnTempTA, 40);
    lv_obj_set_height(ui_fanOnTempTA, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_fanOnTempTA, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_fanOnTempTA, NULL);
    else lv_textarea_set_accepted_chars(ui_fanOnTempTA, "0123456789");
    lv_textarea_set_max_length(ui_fanOnTempTA, 2);
    lv_textarea_set_placeholder_text(ui_fanOnTempTA, "--");
    lv_textarea_set_one_line(ui_fanOnTempTA, true);
    lv_obj_clear_flag(ui_fanOnTempTA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_fanOnTempTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOnTempTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fanOnTempTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_fanOnTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fanOnTempTA, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fanOnTempTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fanOnTempTA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_fanOnTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_fanOnTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_fanOnTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_fanOnTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_fanOnTempTA, lv_color_hex(0xA4A5A4), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOnTempTA, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(95));
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Time between on cycles (min):   ");

    ui_fanOffTempTA = lv_textarea_create(ui_Container8);
    lv_obj_set_width(ui_fanOffTempTA, 40);
    lv_obj_set_height(ui_fanOffTempTA, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_fanOffTempTA, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_fanOffTempTA, NULL);
    else lv_textarea_set_accepted_chars(ui_fanOffTempTA, "0123456789");
    lv_textarea_set_max_length(ui_fanOffTempTA, 3);
    lv_textarea_set_placeholder_text(ui_fanOffTempTA, "--");
    lv_textarea_set_one_line(ui_fanOffTempTA, true);
    lv_obj_clear_flag(ui_fanOffTempTA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_fanOffTempTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOffTempTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fanOffTempTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_fanOffTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fanOffTempTA, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fanOffTempTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fanOffTempTA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_fanOffTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_fanOffTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_fanOffTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_fanOffTempTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_fanOffTempTA, lv_color_hex(0xA4A5A4), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOffTempTA, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_tempCont);
    lv_obj_set_width(ui_Label20, 150);
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 20);
    lv_obj_set_y(ui_Label20, 0);
    lv_label_set_text(ui_Label20, "Temperature Vent.");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label20, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aqCont = lv_obj_create(ui_ventSetPanel);
    lv_obj_remove_style_all(ui_aqCont);
    lv_obj_set_width(ui_aqCont, lv_pct(100));
    lv_obj_set_height(ui_aqCont, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_aqCont, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_aqCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_aqCont);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 7);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(95));
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Run fan below AQ level (%):   ");

    ui_aqMinTA = lv_textarea_create(ui_Container4);
    lv_obj_set_width(ui_aqMinTA, 40);
    lv_obj_set_height(ui_aqMinTA, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_aqMinTA, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_aqMinTA, NULL);
    else lv_textarea_set_accepted_chars(ui_aqMinTA, "0123456789");
    lv_textarea_set_max_length(ui_aqMinTA, 2);
    lv_textarea_set_placeholder_text(ui_aqMinTA, "--");
    lv_textarea_set_one_line(ui_aqMinTA, true);
    lv_obj_clear_flag(ui_aqMinTA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_aqMinTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aqMinTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_aqMinTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_aqMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_aqMinTA, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aqMinTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_aqMinTA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_aqMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_aqMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_aqMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_aqMinTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_aqMinTA, lv_color_hex(0xA4A5A4), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aqMinTA, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, lv_pct(95));
    lv_obj_set_height(ui_Container12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Fan on time (min):   ");

    ui_fanOnAqTA = lv_textarea_create(ui_Container12);
    lv_obj_set_width(ui_fanOnAqTA, 40);
    lv_obj_set_height(ui_fanOnAqTA, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_fanOnAqTA, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_fanOnAqTA, NULL);
    else lv_textarea_set_accepted_chars(ui_fanOnAqTA, "0123456789");
    lv_textarea_set_max_length(ui_fanOnAqTA, 2);
    lv_textarea_set_placeholder_text(ui_fanOnAqTA, "--");
    lv_textarea_set_one_line(ui_fanOnAqTA, true);
    lv_obj_clear_flag(ui_fanOnAqTA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_fanOnAqTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOnAqTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fanOnAqTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_fanOnAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fanOnAqTA, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fanOnAqTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fanOnAqTA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_fanOnAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_fanOnAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_fanOnAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_fanOnAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_fanOnAqTA, lv_color_hex(0xA4A5A4), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOnAqTA, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, lv_pct(95));
    lv_obj_set_height(ui_Container13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Time between on cycles (min):   ");

    ui_fanOffAqTA = lv_textarea_create(ui_Container13);
    lv_obj_set_width(ui_fanOffAqTA, 40);
    lv_obj_set_height(ui_fanOffAqTA, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_fanOffAqTA, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_fanOffAqTA, NULL);
    else lv_textarea_set_accepted_chars(ui_fanOffAqTA, "0123456789");
    lv_textarea_set_max_length(ui_fanOffAqTA, 2);
    lv_textarea_set_placeholder_text(ui_fanOffAqTA, "--");
    lv_textarea_set_one_line(ui_fanOffAqTA, true);
    lv_obj_clear_flag(ui_fanOffAqTA, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_fanOffAqTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOffAqTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fanOffAqTA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_fanOffAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fanOffAqTA, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fanOffAqTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fanOffAqTA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_fanOffAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_fanOffAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_fanOffAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_fanOffAqTA, 5, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_color(ui_fanOffAqTA, lv_color_hex(0xA4A5A4), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fanOffAqTA, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_aqCont);
    lv_obj_set_width(ui_Label28, 70);
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 20);
    lv_obj_set_y(ui_Label28, 0);
    lv_label_set_text(ui_Label28, "AQ Vent.");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xA4A5A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label28, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardVent = lv_keyboard_create(ui_ventTabPage);
    lv_keyboard_set_mode(ui_KeyboardVent, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardVent, lv_pct(49));
    lv_obj_set_height(ui_KeyboardVent, lv_pct(100));
    lv_obj_set_align(ui_KeyboardVent, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_KeyboardVent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KeyboardVent, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardVent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTabPage = lv_tabview_add_tab(ui_setTabView, "System Settings");
    lv_obj_set_flex_flow(ui_setTabPage, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setTabPage, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_setTabPage, lv_color_hex(0x204052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setTabPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_setTabPage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_setTabPage);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Screen TImeout:  ");

    ui_screenTimeDrop = lv_dropdown_create(ui_Container9);
    lv_dropdown_set_options(ui_screenTimeDrop, "0\n10\n20\n30");
    lv_obj_set_width(ui_screenTimeDrop, 70);
    lv_obj_set_height(ui_screenTimeDrop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_screenTimeDrop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_screenTimeDrop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_butRewifi = lv_btn_create(ui_setTabPage);
    lv_obj_set_width(ui_butRewifi, 100);
    lv_obj_set_height(ui_butRewifi, 40);
    lv_obj_set_x(ui_butRewifi, 110);
    lv_obj_set_y(ui_butRewifi, 0);
    lv_obj_set_align(ui_butRewifi, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_butRewifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_butRewifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_butRewifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_butRewifi, lv_color_hex(0x3975F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_butRewifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_butRewifi, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_butRewifi, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label16 = lv_label_create(ui_butRewifi);
    lv_obj_set_width(ui_Label16, 100);
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Reconnect to WiFi");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_butRemqtt = lv_btn_create(ui_setTabPage);
    lv_obj_set_width(ui_butRemqtt, 100);
    lv_obj_set_height(ui_butRemqtt, 40);
    lv_obj_set_x(ui_butRemqtt, 220);
    lv_obj_set_y(ui_butRemqtt, 0);
    lv_obj_set_align(ui_butRemqtt, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_butRemqtt, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_butRemqtt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_butRemqtt, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_butRemqtt, lv_color_hex(0x3975F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_butRemqtt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_butRemqtt, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_butRemqtt, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label17 = lv_label_create(ui_butRemqtt);
    lv_obj_set_width(ui_Label17, 100);
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Reconnect to MQTT");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_butReboot = lv_btn_create(ui_setTabPage);
    lv_obj_set_width(ui_butReboot, 100);
    lv_obj_set_height(ui_butReboot, 40);
    lv_obj_set_align(ui_butReboot, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_butReboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_butReboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_butReboot, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_butReboot, lv_color_hex(0x3975F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_butReboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_butReboot, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_butReboot, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label15 = lv_label_create(ui_butReboot);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Reboot");

    ui_logTabPage = lv_tabview_add_tab(ui_setTabView, "Log");
    lv_obj_set_style_border_color(ui_logTabPage, lv_color_hex(0x204052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_logTabPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_logTabPage, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logLab = lv_label_create(ui_logTabPage);
    lv_obj_set_width(ui_logLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_clear_flag(ui_logLab, LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_logLab, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_logLab, LV_DIR_VER);

    lv_obj_add_event_cb(ui_comp_get_child(ui_FullScreen2, UI_COMP_FULLSCREEN_SIDEBAR3_BUTHOME2),
                        ui_event_FullScreen2_Sidebar3_butHome2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_FullScreen2, UI_COMP_FULLSCREEN_SIDEBAR3_BUTTEMP2),
                        ui_event_FullScreen2_Sidebar3_butTemp2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_targTempMinTA, ui_event_targTempMinTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_absTempMinTA, ui_event_absTempMinTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fanOnTempTA, ui_event_fanOnTempTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fanOffTempTA, ui_event_fanOffTempTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aqMinTA, ui_event_aqMinTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fanOnAqTA, ui_event_fanOnAqTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fanOffAqTA, ui_event_fanOffAqTA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardVent, ui_event_KeyboardVent, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenTimeDrop, ui_event_screenTimeDrop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_butRewifi, ui_event_butRewifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_butRemqtt, ui_event_butRemqtt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_butReboot, ui_event_butReboot, LV_EVENT_ALL, NULL);

}
