// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

    ui_FullScreen = ui_FullScreen_create(ui_Screen1);
    lv_obj_set_x(ui_FullScreen, 0);
    lv_obj_set_y(ui_FullScreen, 0);



    lv_obj_set_style_bg_color(ui_comp_get_child(ui_FullScreen, UI_COMP_FULLSCREEN_SIDEBAR3_BUTHOME2),
                              lv_color_hex(0x84A98C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_FullScreen, UI_COMP_FULLSCREEN_SIDEBAR3_BUTHOME2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label1 = lv_label_create(ui_comp_get_child(ui_FullScreen, UI_COMP_FULLSCREEN_CONTENTCONTAINER));
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Home Page");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
