// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScrCharts_screen_init(void)
{
    ui_ScrCharts = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrCharts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FullScreen1 = ui_FullScreen_create(ui_ScrCharts);
    lv_obj_set_x(ui_FullScreen1, 0);
    lv_obj_set_y(ui_FullScreen1, 0);



    lv_obj_set_style_bg_color(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_SIDEBAR3_BUTTEMP2),
                              lv_color_hex(0x84A98C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_SIDEBAR3_BUTTEMP2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Chart1 = lv_chart_create(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_CONTENTCONTAINER));
    lv_obj_set_width(ui_Chart1, lv_pct(95));
    lv_obj_set_height(ui_Chart1, lv_pct(85));
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, -25);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_BOTTOM_RIGHT);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 300);
    lv_chart_set_div_line_count(ui_Chart1, 10, 10);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);


    lv_obj_set_style_size(ui_Chart1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_CONTENTCONTAINER));
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 35);
    lv_obj_set_x(ui_Button1, -210);
    lv_obj_set_y(ui_Button1, -212);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_but2H = lv_btn_create(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_CONTENTCONTAINER));
    lv_obj_set_width(ui_but2H, 50);
    lv_obj_set_height(ui_but2H, 30);
    lv_obj_set_align(ui_but2H, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_but2H, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_but2H, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_but2H, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_but2H, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_but2H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_but2H, lv_color_hex(0x4C8E74), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_but2H, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_but2H);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "2H");

    ui_but30m = lv_btn_create(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_CONTENTCONTAINER));
    lv_obj_set_width(ui_but30m, 50);
    lv_obj_set_height(ui_but30m, 30);
    lv_obj_set_x(ui_but30m, -110);
    lv_obj_set_y(ui_but30m, 0);
    lv_obj_set_align(ui_but30m, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_but30m, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_but30m, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_but30m, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_but30m, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_but30m, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_but30m, lv_color_hex(0x4C8E74), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_but30m, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label7 = lv_label_create(ui_but30m);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "30m");

    ui_but1H = lv_btn_create(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_CONTENTCONTAINER));
    lv_obj_set_width(ui_but1H, 50);
    lv_obj_set_height(ui_but1H, 30);
    lv_obj_set_x(ui_but1H, -55);
    lv_obj_set_y(ui_but1H, 0);
    lv_obj_set_align(ui_but1H, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_but1H, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_but1H, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_but1H, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_but1H, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_but1H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_but1H, lv_color_hex(0x4C8E74), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_but1H, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label6 = lv_label_create(ui_but1H);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "1H");

    lv_obj_add_event_cb(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_SIDEBAR3_BUTHOME2),
                        ui_event_FullScreen1_Sidebar3_butHome2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_FullScreen1, UI_COMP_FULLSCREEN_SIDEBAR3_BUTAQ2),
                        ui_event_FullScreen1_Sidebar3_butAQ2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_but2H, ui_event_but2H, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_but30m, ui_event_but30m, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_but1H, ui_event_but1H, LV_EVENT_ALL, NULL);

}
