// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT FullScreen

lv_obj_t * ui_FullScreen_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_FullScreen;
    cui_FullScreen = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_FullScreen);
    lv_obj_set_width(cui_FullScreen, lv_pct(100));
    lv_obj_set_height(cui_FullScreen, lv_pct(100));
    lv_obj_set_align(cui_FullScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_FullScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Sidebar3;
    cui_Sidebar3 = lv_obj_create(cui_FullScreen);
    lv_obj_remove_style_all(cui_Sidebar3);
    lv_obj_set_width(cui_Sidebar3, lv_pct(10));
    lv_obj_set_height(cui_Sidebar3, lv_pct(100));
    lv_obj_set_align(cui_Sidebar3, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(cui_Sidebar3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Sidebar3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Sidebar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_butHome2;
    cui_butHome2 = lv_btn_create(cui_Sidebar3);
    lv_obj_set_width(cui_butHome2, lv_pct(100));
    lv_obj_set_flex_grow(cui_butHome2, 1);
    lv_obj_set_x(cui_butHome2, -110);
    lv_obj_set_y(cui_butHome2, 93);
    lv_obj_set_align(cui_butHome2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_butHome2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_butHome2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_butHome2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_butHome2, lv_color_hex(0x595959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_butHome2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(cui_butHome2, &ui_img_home_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_butHome2, lv_color_hex(0x84A98C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_butHome2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_butTemp2;
    cui_butTemp2 = lv_btn_create(cui_Sidebar3);
    lv_obj_set_width(cui_butTemp2, lv_pct(100));
    lv_obj_set_flex_grow(cui_butTemp2, 1);
    lv_obj_set_x(cui_butTemp2, -110);
    lv_obj_set_y(cui_butTemp2, 93);
    lv_obj_set_align(cui_butTemp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_butTemp2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_butTemp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_butTemp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_butTemp2, lv_color_hex(0x595959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_butTemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(cui_butTemp2, &ui_img_2110918543, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_butTemp2, lv_color_hex(0x84A98C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_butTemp2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_butAQ2;
    cui_butAQ2 = lv_btn_create(cui_Sidebar3);
    lv_obj_set_width(cui_butAQ2, lv_pct(100));
    lv_obj_set_flex_grow(cui_butAQ2, 1);
    lv_obj_set_x(cui_butAQ2, -110);
    lv_obj_set_y(cui_butAQ2, 93);
    lv_obj_set_align(cui_butAQ2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_butAQ2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_butAQ2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_butAQ2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_butAQ2, lv_color_hex(0x595959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_butAQ2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(cui_butAQ2, &ui_img_267769087, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_butAQ2, lv_color_hex(0x84A98C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_butAQ2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_ContentContainer;
    cui_ContentContainer = lv_obj_create(cui_FullScreen);
    lv_obj_remove_style_all(cui_ContentContainer);
    lv_obj_set_width(cui_ContentContainer, lv_pct(90));
    lv_obj_set_height(cui_ContentContainer, lv_pct(100));
    lv_obj_set_align(cui_ContentContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(cui_ContentContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_ContentContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ContentContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ContentContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ContentContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_FULLSCREEN_NUM);
    children[UI_COMP_FULLSCREEN_FULLSCREEN] = cui_FullScreen;
    children[UI_COMP_FULLSCREEN_SIDEBAR3] = cui_Sidebar3;
    children[UI_COMP_FULLSCREEN_SIDEBAR3_BUTHOME2] = cui_butHome2;
    children[UI_COMP_FULLSCREEN_SIDEBAR3_BUTTEMP2] = cui_butTemp2;
    children[UI_COMP_FULLSCREEN_SIDEBAR3_BUTAQ2] = cui_butAQ2;
    children[UI_COMP_FULLSCREEN_CONTENTCONTAINER] = cui_ContentContainer;
    lv_obj_add_event_cb(cui_FullScreen, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_FullScreen, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_FullScreen_create_hook(cui_FullScreen);
    return cui_FullScreen;
}

