// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_FULLSCREEN_H
#define _UI_COMP_FULLSCREEN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT FullScreen
#define UI_COMP_FULLSCREEN_FULLSCREEN 0
#define UI_COMP_FULLSCREEN_SIDEBAR3 1
#define UI_COMP_FULLSCREEN_SIDEBAR3_BUTHOME2 2
#define UI_COMP_FULLSCREEN_SIDEBAR3_BUTTEMP2 3
#define UI_COMP_FULLSCREEN_SIDEBAR3_BUTAQ2 4
#define UI_COMP_FULLSCREEN_CONTENTCONTAINER 5
#define _UI_COMP_FULLSCREEN_NUM 6
lv_obj_t * ui_FullScreen_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
